### ISSUE TITLE
Ideas: Make some channel point rewards involving things like spawning the ender dragon, spawning a charged creeper, spawning the wither, spawning BEE, and also like a jumpscare.

### ISSUE THREAD

**Issue by pikchu87** [sh0ckR6/hardcore-twitch-integration#4]
For the ender dragon and wither they should be really expensive. Maybe like 5k or more. For the charged creeper maybe it could be 1.5k or more. BEE could probaly be like 500 as it is just BEE. And for the jumscare maybe like the  thing that happens when you get mining fatiuge and some sort of sound, probaly for 1k or less. 
Anyways please consider some of these ideas.

**Comment by sh0ckR6** [comment]
I like the ideas! I might play around a bit with the prices of each of the items, but I might not add everything. I'll take a look in the morning and go from there!

*Also, I'm probably going to move ender dragon from channel points to bits just because it's so powerful!*
~ sh0ck

**Comment by sh0ckR6** [comment]
I linked the pull request of the suggested changes, let me know if they're fine

# Changes

## [Feature/Channel Points] Add "Bee"
*summons a bee, what else would it do?*

**Suggested Price**: 100 points

## [Feature/Channel Points] Add "jumpscare"
*Boo!*

Add potion effects:
- **Mining Fatigue** (2 seconds)
- **Blindness** (2 seconds)

Plays sounds:
- **Creeper primed**

## [Feature/Bits] Add "summoning ender dragon"
*I think you're here a little early...*

**Suggested Price**: 6666 bits
**\*\*Replaces previous reward at 6666 bits (5 witches, 5 blazes)\*\***

## [Change/Bits] Change price of 5 witches, 5 blazes
*Might've been a little to high...*

**New Price**: 4200 bits
**Old Price**: 6666 bits

**Comment by sh0ckR6** [comment]
I'm gonna go ahead and merge the changes, prices are really the only discussion point atm and those don't exactly relate to the repo.
